:imagesdir: media/
= Setup
Set up the developer environment, create, build, and deploy and application.

== Install Enonic CLI

The Enonic CLI (Command Line Interface) is an essential tool for developing with Enonic.

If you have `npm` on your device, run this command:

  npm install -g @enonic/cli

If not, here are some https://developer.enonic.com/start[alternative ways to install Enonic CLI^]

To verify that the CLI has been installed, run `enonic -v`. This should output the version of your installed CLI. To see all available options, simply run `enonic`.

TIP: To upgrade, use `enonic latest`. If there are new versions you will see instructions on how to upgrade.

== Create a sandbox

A sandbox is a local developer instance of our platform - Enonic XP. Each sandbox is isolated from the other ones and can run different versions of the platform.

. **Create a sandbox** by running this command in your terminal:
+
  enonic sandbox create
+
Give it a name, i.e. `Tutorial`, and agree to continue with the most recent version of Enonic XP. The CLI will proceed to download and setup your local developer instance, i.e, your sandbox.
+
. **Start the sandbox** with this command:
+
  enonic sandbox start --dev
+
Select the `Tutorial` sandbox from the list, and it will boot up in development mode.

TIP: --dev starts the sandbox in https://developer.enonic.com/docs/xp/stable/dev/build#dev_mode[developer mode].

== Create the app

From a **new terminal window**, run the following command to create the application.

IMPORTANT: Use the default options when prompted.

  enonic project create -r tutorial-myfirstsite

[TIP]
====
The command uses the https://github.com/enonic/tutorial-myfirstsite[My first site^] Github repo  as a starter (template) for the app.
====

== Project structure

The project folder created should now contain a basic app structure, looking something like this:

[source,files]
----
build.gradle //<1>
build/ //<2>
code-samples/ //<3>
docs/ //<4>
src/
  main/
    resources/
      import/ //<5>
      assets/ //<6>
      sites/
        content-types/ //<7>
          country/
          city/
        parts/ //<8>
        pages/ //<9>
----

<1> Gradle files are used by the build system
<2> Contains output files produced by the build
<3> Code samples that will be used in this tutorial
<4> Contains the documentation you are reading now
<5> Contains sample content that is imported when the app starts
<6> Location for static assets
<7> Two pre-defined content types, country and city
<8> Part components - leaf components to place on pages
<9> Page components - root component for pages

== Building

Assuming you did not change the default directory name `myproject/` when creating the app, build it with the following commands:

  cd myproject
  enonic project dev

This will build and deploy the application to your sandbox, the `dev` task is set up to continuously scan for changes in your code and compile them.

[NOTE]
====
Look for a line like this in the sandbox log to verify that the app has started:

  2019-04-09 13:40:40,765 INFO ... Application [company.starter.myfirstsite] installed successfully
====

TIP: Thanks to the sandbox running in --dev mode, any changes to the code wihin your app will instantly be picked up.


== Summary

You have installed the Enonic CLI, created your first sandbox using the latest XP version, deployed an app to that sandbox based on one of our starters, executed CLI commands to `build` your app , `deploy` it to your sandbox, and run the app in `dev` mode, and finally, installed Content Studio app.

That's a good start! 

Next, let's <<content#, have a look at Content Studio>> and some sample content.