:imagesdir: media/

= Setting up the developer environment

Set up the developer environment, create, build, and deploy and application.

== Install Enonic CLI

The Enonic CLI (Command Line Interface) is an essential tool for developing with Enonic.

If you have `npm` on your device, run this command:

  npm install -g @enonic/cli

If not, here are some https://developer.enonic.com/start[alternative ways to install Enonic CLI^]

To verify that the CLI has been installed, run `enonic -v`. This should output the version of your installed CLI. To see all available options, simply run `enonic`.

TIP: To upgrade, use `enonic latest`. If there are new versions you will see instructions on how to upgrade.

== Create a sandbox

A sandbox is a local developer instance of our platform - Enonic XP. Each sandbox is isolated from the other ones and can run different versions of the platform.

. *Create a sandbox* called `mfstutorial` by running this command in your terminal:
+
  enonic sandbox create mfstutorial
+
Agree to continue with the most recent version of Enonic XP. The CLI will proceed to download and setup your local developer instance, i.e, your sandbox.
+
. **Start the sandbox** with this command:
+
  enonic sandbox start mfstutorial --dev
+
This will start the `mfstutorial` sandbox.

TIP: --dev starts the sandbox in https://developer.enonic.com/docs/xp/stable/dev/build#dev_mode[developer mode].

== Create the app

From a **new terminal window**, run the following command to create the application. 

  enonic project create -d mfs -r tutorial-myfirstsite -sb mfstutorial my.first.site

[NOTE]
====
This command creates an app named `my.first.site` in the folder `mfs/`. It uses the https://github.com/enonic/tutorial-myfirstsite[My first site^] Github repo  as a starter (template), and links it to the `mfstutorial` sandbox. 
====

== Project structure

The project folder created should now contain a basic app structure, looking something like this:

[source,files]
----
build.gradle //<1>
build/ //<2>
code-samples/ //<3>
docs/ //<4>
tsup/ //<5>
src/
  main/
    resources/
      import/ //<6>
      assets/ //<7>
      sites/
        content-types/ //<8>
          country/
          city/
        parts/ //<9>
        pages/ //<10>
----

<1> Core build files
<2> Contains output files produced by the build
<3> Code samples that will be used in this tutorial
<4> Contains the documentation you are reading now
<5> TSUP typescript compilation build files
<6> Contains sample content that is imported when the app starts
<7> Location for static assets
<8> Two pre-defined content types, country and city
<9> Part components - leaf components to place on pages
<10> Page components - root component for pages

== Start building

Assuming you did not change any of the values when creating the app, run the following commmands:

  cd mfs
  enonic dev

This will build and deploy the application to your sandbox. Until you abort, the build system will continuously scan for changes in your TypeScript code and compile them.

[NOTE]
====
Look for a line like this in the sandbox log to verify that the app has started:

  2019-04-09 13:40:40,765 INFO ... Application [my.first.site] installed successfully
====

TIP: Because the sandbox is running in --dev mode, any changes to the code wihin your app will instantly be picked up. No need for manual deployments.


== Summary

You have installed the Enonic CLI, created your first sandbox using the latest XP version, deployed an app to that sandbox based on one of our starters and deployed the app in `dev` mode.

That's a good start! 

Next, let's <<content#, have a look at Content Studio>> and the sample content.